extends: airbnb-base
parser: babel-eslint

rules:
  max-classes-per-file: 'off'
  class-methods-use-this: 'off'
  object-curly-newline: 'off'
  no-unused-vars:
    - 'error'
    - argsIgnorePattern: '^_'

env:
  jest: true
