name: Run static analysis and tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install deps
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Type check
        run: yarn flow
      - name: Run tests
        run: yarn test

